export const LANG_DE_NAME = 'DE';

export const LANG_DE_TRANS = {
  'CURRENCY': '€',
  'NEWS': 'Neuheiten',
  'ABOUT_US': 'Über McLED',
  'REFERENCE': 'Referenz',
  'DOWNLOAD': 'Download',
  'CONTACT': 'Kontakt',
  'B2B': 'B2B',
  '/news': '/neuheiten',
  '/about-us': '/ueber-mcled',
  '/reference': '/referenz',
  '/download': '/download',
  '/contact': '/kontakt',
  '/basket': '/korb',
  '/b2b': '/b2b',
  '/shipping-and-payment': '/lieferung-und-zahlung',
  '/personal-data': '/peronliche-daten',
  '/terms-and-conditions': '/allgemeine-geschaeftsbedingungen',
  '/lost-password': '/kennwort-vergessen',
  '/registration': '/registrierung',
  '/registration-success': '/registrierung-erfolgreich ',
  '/datasheet': '/produktblatt',
  '/order-summary': '/bestellung-zusammenfassen',
  '/thanks': '/danke',
  'sales@mcled.cz': 'mcled.sales@schmachtl.at',
  'support@mcled.cz': 'mcled.support@schmachtl.at',
  'office@mcled.cz': 'mcled.office@schmachtl.at',
  'www.mcled.cz': 'www.mcled.at',
  '+420 220 184 828, +420 220 184 820': '+43 732 7646 26, +43 732 7646 738',
  '+420 220 184 886': '+43 732 7646 26, +43 732 7646 738',
  '+420 220 184 800': '+43 732 764 60',
  '220 184 800': '+43 732 764 60',
  'tel.: +420 220 184 886': '+43 732 7646 26, +43 732 7646 738',
  'Vyberte délku profilu z&nbsp;tabulky a&nbsp;zvolte příslušenství': 'Profillänge in Tabelle wählen und passendes Zubehör wählen',
  'Do košíku': 'In den Korb',
  'bez DPH': 'ohne MwSt.',
  'Celkem bez DPH': 'Summe ohne MwSt.',
  'Kód': 'Art.nr.',
  'Produktový list': 'Datenblatt',
  'Tisknout': 'Drucken',
  'McLED Asist': 'McLED Support',
  'Novinka': 'Neuheit',
  'Akce': 'Aktion',
  'Parametry': 'Techn. Daten',
  'Detailní popis': 'Detailierte Beschreibung',
  'Ke stažení': 'Download',
  'Foto': 'Foto',
  'Video': 'Video',
  'Vyberte způsob platby': 'Zahlungsmöglichkeit wählen',
  'zdarma': 'kostenlos',
  'Vyberte způsob dopravy': 'Liefermöglichkeit wählen',
  'Výsledky vyhledávání pro': 'Suchergebnisse für',
  'Zobrazit': 'Anzeigen',
  'z': 'aus',
  'položek': 'Artikel',
  'Skladem': 'Lagernd',
  'Částečně': 'Teilweise',
  'Na poptávku': 'Auf Anfrage',
  'Řazení': 'Sortieren',
  'Příslušenství': 'Zubehör',
  'Příslušenství nebylo nalezeno': 'Zubehör nicht gefunden',
  'Popis': 'Beschreibung',
  'Pásek': 'Band',
  'Počet': 'Menge',
  'Cena bez DPH': 'Preis ohne MwSt.',
  'Dostupnost': 'Verfügbarkeit',
  'Přívod B': 'Zuführung B',
  'Přívod "B"': 'Zuführung B',
  'Přívod A': 'Zuführung A',
  'Přívod "A"': 'Zuführung A',
  'Délka': 'Länge',
  'Základní délky pásku': 'Bandgrundlänge',
  'Základní délky pásku nebyly nalezeny': 'Bandgrundlänge nicht gefunden',
  'Konfigurace tohoto produktu zatím není dostupná': 'Produktkonfigurierung zur Zeit nicht möglich',
  'Individuální délka pásku a přívodu – zakázková výroba': 'Individuelle Band.-und Zufürungslänge',
  'Zvolit délku': 'Länge wählen',
  'Košík': 'Korb',
  'Doprava a platba': 'Lieferung und Zahlung',
  'Osobní údaje': 'Firmendaten',
  'Shrnutí objednávky': 'Zusammenfassen',
  'Zpět': 'Zurück',
  'Pokračovat': 'Fortfahren',
  'Už jsem zde nakupoval/a a chci se': 'Ich bin schon registriert und möchte mich',
  'přihlásit': 'anmelden',
  'Po přihlášení předvyplníme vaše osobní údaje do formuláře níže': 'Ihre persönlichen Daten werden bei der Anmeldung vorab ausgefüllt, siehe Formular unten',
  'Zpět do obchodu': 'Zurück zum Shop',
  'Do dopravy': 'In die Lieferung',
  'ZDARMA': 'KOSTENLOS',
  'zbývá': 'es fehlen',
  'Cena celkem s DPH': 'Gesamtpreis inkl. MwSt.',
  'Cena celkem bez DPH': 'Gesamtpreis ohne MwSt.',
  'Použít': 'Einlösen',
  'Odstranit': 'Entfernen',
  'Kód poukazu': 'Gutschein-Code',
  'Mám slevový poukaz': 'Gutschein einlösen',
  'Přidat do košíku': 'in den Korb',
  'Počet kusů': 'Stückzahl',
  'Objednací kód': 'Art.nr.',
  'Přidat zboží': 'Ware hinzufügen',
  'Nelze měnit, přidáno z konfigurátoru.': 'Keine Änderung möglich, vom Konfigurator zugefügt.',
  'Odebráním odstraníte související produkty z konfigurace.': 'Beim Entnehmen werden zusammenhängende Produkte aus der Konfiguration entfernt.',
  'Odstranit z košíku': 'Aus Korb enfernen',
  'Cena za kus': 'Preis pro Stück',
  'bez DPH vč. slevy': 'ohne MwSt., inkl. Rabatt',
  'Cena celkem': 'Gesamtpreis',
  'Zboží': 'Ware',
  'Celková cena vč. DPH': 'Gesamtpreis inkl. MwSt.',
  'Platba': 'Zahlung',
  'Doprava': 'Lieferung',
  'Cena za zboží': 'Preis',
  'Rekapitulace objednávky': 'Rekapitulation der Bestellung',
  'Celkem': 'Gesamt',
  'Infolinka': 'Support',
  'Zadejte hledaný výraz': 'Suchbegriff eingeben',
  'Vyhledávání': 'Suche',
  'Odeslat objednávku': 'Bestellung senden',
  'Fakturační údaje': 'Registrierung',
  'Dodací údaje': 'Lieferadresse',
  'Odesláním objednávky souhlasíte s': 'It Senden der Bestellung akzeptieren Sie unsere',
  'obchodními podmínkami': 'Geschäftsbedingungen',
  'internetového obchodu': 'Internetgeschäft',
  'tel.': 'Tel.',
  'Váš e-mail': 'Ihre E-Mail',
  'Vaše jméno': 'Ihr Name',
  'Text dotazu': 'Fragetext',
  'Odeslat': 'Versenden',
  'Položky označené': 'Die mit einem',
  'je nutné vyplnit': 'markierten Felder sind Pflichtfelder.',
  'Nahrávám přílohy': 'Anlage laden',
  'Došlo k chybě při vložení do košíku, produkty se neuložily.': 'Fehler beim Zufügen in den Korb aufgetreten.',
  'Zvolte jednostranné nebo oboustranné napájení LED pásku': 'Wähle einseitigen oder beidseitigen Anschluss des LED Bandes',
  'Při délkách pásku nad': 'Bei Bandlänge von über',
  'doporučujeme zvolit oboustranné napájení': 'empfehlen wir beidseitigen Anschluss',
  'Jednostranné napájení': 'Einseitiger Anschluss',
  'maximální délka LED pásku': 'maximale LED Bandänge',
  'Oboustranné napájení': 'Beidseitiger Anschluss',
  'Zvolte délku pásku': 'Bandlänge wählen',
  'pásek lze zkracovat po modulech': 'Band in Modulen kürzbar',
  'Zohledněte délky koncovek, délku LED pásku, prostor pro vstup vodiče do profilu a pro připojení vodiče k LED pásku': 'Berücksichtigen Sie die Länge der Endstücke, LED Bandlänge, Platz für Kabelzugang ins Profil und Anschluss zum LED Band',
  'Zvolte délku napájecího vodiče LED pásku': 'Wähle Länge des Anschlusskabels zum LED Band',
  'Celková maximální doporučená délka napájecího vodiče (průřez 0,5 mm2) je pro tento typ LED pásku': 'Empfohlene Maximallänge des Anschlusskabels (Durchmesser 0,5 mm2) ist für dieses LED Band',
  'Zvolená délka': 'Gewählte Länge',
  'Přívod': 'Zuleitung',
  'Zvolit': 'Wählen',
  'Délka napájení': 'Anschlusslänge',
  'Délka pásku': 'Bandlänge',
  'Zvolte délku profilu': 'Profillänge wählen',
  'Výchozí': 'Sortieren',
  'Cena vzestupně': 'Preis aufsteigend',
  'Cena sestupně': 'Preis absteigend',
  'Kód vzestupně': 'Art.nr. aufsteigend',
  'Kód sestupně': 'Art.nr. absteigend',
  'Název vzestupně': 'Name aufsteigend',
  'Název sestupně': 'Name absteigend',
  'Základní filtr': 'Filter',
  'Rozšířený filtr': 'Erweiterter Filter',
  'Patice': 'Fassung',
  'Výška': 'Höhe',
  'chip': 'Chip',
  'Napájení': 'Einspeisung',
  'Příkon': 'Leistung',
  'Šířka': 'Breite',
  'Barvy': 'Farbe',
  'Náhrada za': 'Ersatz',
  'Typ trubice': 'Röhrentyp',
  'E-mail / Login': 'E-mail / Login',
  'Heslo': 'Kennwort',
  'Přihlásit': 'Anmelden',
  'Zapomenuté heslo': 'Kennwort vergessen',
  'Neplatné jméno nebo heslo.': 'Ungültiger Name oder Kennwort.',
  'Zadejte login a heslo.': 'Login und Kennwort eingeben.',
  'Přihlásit se': 'Anmelden',
  'Odhlásit': 'Abmelden',
  'Česky': 'Tschechisch',
  'Newsletter': 'Newsletter',
  'Nechte si zasílat novinky o výhodných akcích': 'Bleiben Sie über Neuheiten und Aktionen informiert',
  'Přihlášení uživatele': 'Benutzer anmelden',
  'Pokud u nás nemáte založený účet, můžete se registrovat': 'ie haben noch kein Konto? Hier können Sie sich registrieren.',
  'Nová registrace': 'Registrierung',
  'Děkujeme za objednávku': 'Danke für Ihre Bestellung',
  'Vážený zákazníku': 'Sehr geehrter Kunde',
  'objednávka byla přijata a její kopie zaslána na vaši e-mailovou adresu.': 'Vielen Dank für Ihre Bestellung. Sie erhalten in Kürze eine Auftragsbestätigung an die eingegebene E-Mail-Adresse.',
  'O jejím aktuálním stavu vás budeme informovat.': 'Über den aktuellen Stand, werden wir Sie informieren.',
  'Pokud máte nějaké dotazy či připomínky, neváhejte nás kontaktovat': 'Haben Sie Fragen oder Anmerkungen? Bitte kontaktieren Sie uns.',
  'na tel. čísle': 'unter Tel. Nummer',
  'nebo na e-mailu': 'oder E-Mail',
  'Načíst další': 'Nächste Seite',
  'Předchozí': 'Vorige',
  'Další': 'Nächste',
  'Nakupujte u našich partnerů': 'Kaufen Sie bei unseren Partnern',
  'Registrace': 'Registrierung',
  'Přihlašovací údaje': 'Anmeldedaten',
  'Login': 'Login',
  'Potvrdit heslo': 'Kennwort bestätigen',
  'Chci se zároveň registrovat': 'Will mich gleichzeitig registrieren',
  'Jméno': 'Vorname',
  'Příjmení': 'Nachname',
  'Telefon': 'Telefon',
  'Město': 'Stadt',
  'Ulice': 'Strasse und Nr.',
  'PSČ': 'PLZ',
  'Stát': 'Staat',
  'Firemní údaje': 'Firmendaten',
  'Firma': 'Firma',
  'IČ': 'ID',
  'DIČ': 'STNR',
  'Dodací adresa je jiná než fakturační': 'Lieferadresse ist eine andere, als die Rechnungsadresse',
  'Souhlasím se zasíláním novinek': 'Newsletter abonnieren',
  'Registrovat': 'Registrierung',
  'Uložit': 'Speichern',
  'Poznámka': 'Anmerkung',
  'Vaše registrace proběhla úspěšně': 'Ihre Registrierung war erfolgreich',
  'Přihlašovací údaje Vám byly zaslány na zadaný e-mail': 'Anmeldedaten wurden an eingegebene e-mail gesendet',
  'Načítám dopravu a platbu': 'Lade Lieferung und Zahlung',
  'Podobné produkty': 'Ähnliche Produkte',
  'Žádný podobný produkt nebyl nalezen': 'Kein ähnliches Produkt gefunden',
  'ks': 'Stk.',
  'Na objednání': 'Auf Bestellung',
  'nepřihlášen': 'unangemeldet',
  'Neplatný kupón': 'ungültiger Gutschein',
  'Chyba při mazání kupónu': 'Fehler beim löschen des Gutscheines',
  'Nepodařilo se vložit kupón': 'Gutschein einfügen ist fehlgeschlagen',
  'Nepodařilo se vytvořit objednávku': 'Bestellung erstellen ist fehlgeschlagen',
  'V košíku nemáte žádné zboží': 'Ihr Warenkorb ist leer',
  'Není vybraný způsob dopravy': 'Keine Art der Lieferung ausgewählt',
  'Není vybraný způsob platby': 'Keine Art der Zahlung ausgewählt',
  'Není zadáno jméno uživatele': 'Kein Benutzervorname eingegeben',
  'Není zadáno příjmení uživatele': 'Kein Benutzernachname eingegeben',
  'Není zadán email uživatele': 'Kein Benutzer E-mail eingegeben',
  'Nepodařilo se přihlásit': 'Anmeldung fehlgeschlagen',
  'Nepodařilo se odhlásit': 'Abmeldung fehlgeschlagen',
  'Chybné jméno nebo heslo': 'Falscher Name oder Kennwort',
  'Login není vyplněn': 'Login nicht ausgefüllt',
  'Uživatelský profil byl uložen': 'Benutzerprofil wurde gespeichert',
  'Email je neplatný': 'E-mail ist ungültig',
  'Telefon je neplatný': 'Telefonnummer ist ungültig',
  'PSČ je neplatné': 'PLZ ist ungültig',
  'Jméno není vyplněno': 'Vorname fehlt',
  'Příjmení není vyplněno': 'Nachname fehlt',
  'Email není vyplněn': 'E-mail fehlt',
  'Telefon není vyplněn': 'Telefonnummer fehlt',
  'Ulice není vyplněna': 'Straße fehlt',
  'Město není vyplněno': 'Stadt fehlt',
  'PSČ není vyplněno': 'PLZ nicht ausgefüllt',
  'Heslo není vyplněno': 'Kennwort fehlt',
  'Heslo a heslo pro ověření musí být stejné': 'Kennwort und Kennwort zur Überprüfung muss gleich sein',
  'Heslo pro ověření není vyplněno': 'Kennwort zur Überprüfung nicht ausgefüllt',
  'Zadaný login již existuje, zadejte prosím jiný.': 'Eingegebenes Login existiert bereits, bitte anderes eingeben',
  'Uživatel se zadaným emailem již existuje, zadejte prosím jiný.': 'Benutzer mit eingegebenem E-mail existiert bereits, bitte anderes eingeben.',
  'Chyba při vytváření uživatele.': 'Fehler beim Erstellen des Benutzers.',
  'Chyba při ukládání uživatele.': 'Fehler beim Speichern des Benutzers.',
  'Chyba při vkládání do košíku': 'Fehler beim Einfügen in den Korb',
  'Neplatný email': 'ungültige E-mail',
  'Email byl zaregistrován pro zasílání novinek': 'E-mail wurde für das versenden von Neuigkeiten registriert',
  'Řetězec musí obsahovat alespoň 3 znaky': 'Kette muss mindestens 3 Zeichen beinhlaten',
  '-- nevyplněno --': '-- leer --',
  'Dotaz byl odeslán': 'Anfrage wurde gesendet',
  'Dotaz nebyl odeslán, došlo k chybě': 'Anfrage wurde nicht gesendet, Fehler ist aufgetreten',
  'Nenalezen žádný záznam': 'Keinen Eintrag gefunden',
  'ano': 'ja',
  'Ano': 'Ja',
  'ANO': 'JA',
  'ne': 'keine',
  'Ne': 'Keine',
  'NE': 'KEINE',
  'Novinky': 'Neuheiten',
  'Očekáváme': 'Wir erwarten',
  'Převodem': 'Bank transfer',
  'Bankovním převodem - proforma': 'Banküberweisung - proforma',
  'Hotově (nelze platit kartou)': 'Cash (Kreditkartenzahlung nicht akzeptiert)',
  'Platba při dobírce': 'Die Zahlung in bar bei der Lieferung',
  'Přepravce': 'Transporter',
  'Osobně': 'Persönlich',
  'Kód produktu': 'Art.nr.',
  'Typ produktu': 'Typ produkt',
  'Rakousko': 'Österreich',
  'Česká republika': 'Tschechische Republik',
  'Česko': 'Tschechische Republik',
  'Název': 'Name',
  'Cena': 'Preis',
  'McLED s.r.o., Vídeňská 185, 252 42 Jesenice': 'McLED s.r.o., Pummererstraße 36, 4020 Linz',
  'Pan':'Herr',
  'Paní':'Frau',
  'Oslovení':'Anrede',
  'Pro firemní zákazníky nabízíme výhodné nákupní podmínky':'Für gewerbliche Kunden bieten wir günstige Einkaufsbedingungen',
  'Děkuji, nemám zájem':'Danke, habe kein Interesse',
  'Mám zájem o sjednání obchodních podmínek pro firemní zákazníky (B2B)':'Habe Interesse an Vereinbarung der Einkaufsbedingungen für gewerbliche Kunden (B2B)',
  'Předmět podnikání':'Unternehmenstätigkeit',
  'Webová adresa':'WEB Adresse',
  'Nákupní podmínky':'Einkaufsbedingungen',
  'Váš požadavek byl odeslán.':'Ihre Anforderung wurde abgeschickt.',
  'Děkujeme Vám, že máte zájem stát se našimi B2B obchodními partnery.':'Wir danken Ihnen für Ihr Interesse unser B2B Geschäftspartner zu werden.',
  'Nejpozději do 24h Vás bude kontaktovat naše obchodní oddělení.':'Spätestens in 24 Std. wird Sie unsere Geschäftsabteilung kontaktieren.',
  'V případě zájmu jej neváhejte sami kontaktovat:':'Sie können uns auch gerne selber kontaktieren:',
  'Firma není vyplněna': 'Das Unternehmen ist nicht gefüllt',
  'IČ není vyplněno': 'Steuernummer (St.-Nr.) wird nicht gefüllt',
  'DIČ není vyplněno': 'Umsatzsteuer-Identifikationsnummer (UID-Nr.) ist nicht gefüllt',
  'Předmět podnikání není vyplněn': 'Gegenstand des Unternehmens ist nicht gefüllt',
  'Přihlašovací e-mail / Login': 'E-mail / Login',
  'Přihlašovací e-mail': 'E-mail',
  'Přihlašovací email je neplatný': 'E-mail ist ungültig',
  'Objednání po překročení kreditního limitu': 'Nach der Bestellung Kreditlimit',
  'Zavřít': 'Schliessen',
  'Čekejte prosím, ukládá se množství.': 'Bitte warten sie eingezahlten betrag.',
  'Zpět na přihlášení': 'Zurückkehren anmelden',
  'Firma není platná': 'Das Unternehmen ist nicht gültig',
  'IČ není platné': 'Steuernummer (St.-Nr.) ist nicht gültig',
  'DIČ je neplatné': 'Umsatzsteuer-Identifikationsnummer (UID-Nr.) ist ungültig',
  'v hotovosti': 'v hotovosti',
  'jejich cena bez DPH': 'ihre Preis ohne MWSt.',
  'Váš uživatelský účet má schválené B2B podmínky pro stát ': 'Ihr Benutzerkonto hat die B2B Bedingungen für staatlich anerkannte ',
  'Přihlaste se prosím na webu příslušného státu pomocí tohoto odkazu: ': 'Bitte melden Sie sich an der Stelle des Staates über diesen Link: ',
  'Chyba při odeslání požadavku.': 'Fehler beim Senden der Anfrage.',
  'Heslo bylo zasláno na Váš email.': 'Passwort an Ihre E-Mail gesendet werden.',
  'Ceny jsou uvedeny bez DPH': 'Die preise verstehen sich ohne MWSt',
  'DPC bez DPH': 'UVP Preis',
  'vaše cena': 'ihr preis',
  'Celková cena bez DPH': 'Gesamtpreis ohne Mehrwertsteuer',
  'Dodání do svou pracovních dní při objednávce do 10 hodin.': 'Lieferzeit 2-3 Werkstage bei Bestellung bis 10 Uhr.',
  'Zboží bude odesláno a fakturováno firmou McLED s.r.o. (Česká republika).': 'Die Ware wird geliefert und fakturiert von der Firma McLED s.r.o. (GmbH) aus Tschechien.',
  'Heslo nemá správný tvar (délka minimálně 8 číslic, 1x velké písmeno, 1x malé písmeno, 1x číslice)': 'Das Passwort ist nicht korrekt Form (Länge von mindestens 8 Zeichen, 1 Großbuchstaben , 1 kleiner Brief, 1 Bild)',
};
