export const LANG_CS_NAME = 'CZ';

export const LANG_CS_TRANS = {
  'NEWS': 'Novinky',
  'ABOUT_US': 'O nás',
  'REFERENCE': 'Reference',
  'DOWNLOAD': 'Ke stažení',
  'CONTACT': 'Kontakt',
  'B2B': 'B2B',
  '/news': '/novinky',
  '/about-us': '/o-nas',
  '/reference': '/reference',
  '/download': '/download',
  '/contact': '/kontakt',
  '/b2b': '/b2b',
  '/basket': '/kosik',
  '/personal-data': '/osobni-udaje',
  '/shipping-and-payment': '/doprava-a-platba',
  '/terms-and-conditions': '/obchodni-podminky',
  '/lost-password': '/zapomenute-heslo',
  '/registration': '/registrace',
  '/registration-success': '/registrace-vysledek',
  '/datasheet': '/datovy-list',
  '/order-summary': '/shrnuti-objednavky',
  '/thanks': '/podekovani',
  'sales@mcled.cz': 'sales@mcled.cz',
  'support@mcled.cz': 'support@mcled.cz',
  'office@mcled.cz': 'office@mcled.cz',
  'www.mcled.cz': 'www.mcled.cz',
  '+420 220 184 828, +420 220 184 820': '+420 220 184 828, +420 220 184 820',
  '+420 220 184 886': '+420 220 184 886',
  '+420 220 184 800': '+420 220 184 800',
  '220 184 800': '220 184 800',
  'tel.: +420 220 184 886': '+420 220 184 886',
  'Vyberte délku profilu z&nbsp;tabulky a&nbsp;zvolte příslušenství': 'Vyberte délku profilu z&nbsp;tabulky a&nbsp;zvolte příslušenství',
  'Do košíku': 'Do košíku',
  'bez DPH': 'bez DPH',
  'Celkem bez DPH': 'Celkem bez DPH',
  'Kód': 'Kód',
  'Produktový list': 'Produktový list',
  'Tisknout': 'Tisknout',
  'McLED Asist': 'McLED Asist',
  'Novinka': 'Novinka',
  'Akce': 'Akce',
  'Parametry': 'Parametry',
  'Detailní popis': 'Detailní popis',
  'Ke stažení': 'Ke stažení',
  'Foto': 'Foto',
  'Video': 'Video',
  'Vyberte způsob platby': 'Vyberte způsob platby',
  'zdarma': 'zdarma',
  'Vyberte způsob dopravy': 'Vyberte způsob dopravy',
  'Výsledky vyhledávání pro': 'Výsledky vyhledávání pro',
  'Zobrazit': 'Zobrazit',
  'z': 'z',
  'položek': 'položek',
  'Skladem': 'Skladem',
  'Částečně': 'Částečně',
  'Na poptávku': 'Na poptávku',
  'Řazení': 'Řazení',
  'Příslušenství': 'Příslušenství',
  'Příslušenství nebylo nalezeno': 'Příslušenství nebylo nalezeno',
  'Popis': 'Popis',
  'Pásek': 'Pásek',
  'Počet': 'Počet',
  'Cena bez DPH': 'Cena bez DPH',
  'Dostupnost': 'Dostupnost',
  'Přívod B': 'Přívod B',
  'Přívod "B"': 'Přívod "B"',
  'Přívod A': 'Přívod A',
  'Přívod "A"': 'Přívod "A"',
  'Délka': 'Délka',
  'Základní délky pásku': 'Základní délky pásku',
  'Základní délky pásku nebyly nalezeny': 'Základní délky pásku nebyly nalezeny',
  'Konfigurace tohoto produktu zatím není dostupná': 'Konfigurace tohoto produktu zatím není dostupná',
  'Individuální délka pásku a přívodu – zakázková výroba': 'Individuální délka pásku a přívodu – zakázková výroba',
  'Zvolit délku': 'Zvolit délku',
  'Košík': 'Košík',
  'Doprava a platba': 'Doprava a platba',
  'Osobní údaje': 'Osobní údaje',
  'Shrnutí objednávky': 'Shrnutí objednávky',
  'Zpět': 'Zpět',
  'Pokračovat': 'Pokračovat',
  'Už jsem zde nakupoval/a a chci se': 'Už jsem zde nakupoval/a a chci se',
  'přihlásit': 'přihlásit',
  'Po přihlášení předvyplníme vaše osobní údaje do formuláře níže': 'Po přihlášení předvyplníme vaše osobní údaje do formuláře níže',
  'Zpět do obchodu': 'Zpět do obchodu',
  'Do dopravy': 'Do dopravy',
  'ZDARMA': 'ZDARMA',
  'zbývá': 'zbývá',
  'Cena celkem s DPH': 'Cena celkem s DPH',
  'Cena celkem bez DPH': 'Cena celkem bez DPH',
  'Použít': 'Použít',
  'Odstranit': 'Odstranit',
  'Kód poukazu': 'Kód poukazu',
  'Mám slevový poukaz': 'Mám slevový poukaz',
  'Přidat do košíku': 'Přidat do košíku',
  'Počet kusů': 'Počet kusů',
  'Objednací kód': 'Objednací kód',
  'Přidat zboží': 'Přidat zboží',
  'Nelze měnit, přidáno z konfigurátoru.': 'Nelze měnit, přidáno z konfigurátoru.',
  'Odebráním odstraníte související produkty z konfigurace.': 'Odebráním odstraníte související produkty z konfigurace.',
  'Odstranit z košíku': 'Odstranit z košíku',
  'Cena za kus': 'Cena za kus',
  'bez DPH vč. slevy': 'bez DPH vč. slevy',
  'Cena celkem': 'Cena celkem',
  'Zboží': 'Zboží',
  'Celková cena vč. DPH': 'Celková cena vč. DPH',
  'Platba': 'Platba',
  'Doprava': 'Doprava',
  'Cena za zboží': 'Cena za zboží',
  'Rekapitulace objednávky': 'Rekapitulace objednávky',
  'Celkem': 'Celkem',
  'Infolinka': 'Infolinka',
  'Zadejte hledaný výraz': 'Zadejte hledaný výraz',
  'Vyhledávání': 'Vyhledávání',
  'Odeslat objednávku': 'Odeslat objednávku',
  'Fakturační údaje': 'Fakturační údaje',
  'Dodací údaje': 'Dodací údaje',
  'Odesláním objednávky souhlasíte s': 'Odesláním objednávky souhlasíte s',
  'obchodními podmínkami': 'obchodními podmínkami',
  'internetového obchodu': 'internetového obchodu',
  'tel.': 'tel.',
  'Váš e-mail': 'Váš e-mail',
  'Vaše jméno': 'Vaše jméno',
  'Text dotazu': 'Text dotazu',
  'Odeslat': 'Odeslat',
  'Položky označené': 'Položky označené',
  'je nutné vyplnit': 'je nutné vyplnit',
  'Nahrávám přílohy': 'Nahrávám přílohy',
  'Došlo k chybě při vložení do košíku, produkty se neuložily.': 'Došlo k chybě při vložení do košíku, produkty se neuložily.',
  'Zvolte jednostranné nebo oboustranné napájení LED pásku': 'Zvolte jednostranné nebo oboustranné napájení LED pásku',
  'Při délkách pásku nad': 'Při délkách pásku nad',
  'doporučujeme zvolit oboustranné napájení': 'doporučujeme zvolit oboustranné napájení',
  'Jednostranné napájení': 'Jednostranné napájení',
  'maximální délka LED pásku': 'maximální délka LED pásku',
  'Oboustranné napájení': 'Oboustranné napájení',
  'Zvolte délku pásku': 'Zvolte délku pásku',
  'pásek lze zkracovat po modulech': 'pásek lze zkracovat po modulech',
  'Zohledněte délky koncovek, délku LED pásku, prostor pro vstup vodiče do profilu a pro připojení vodiče k LED pásku': 'Zohledněte délky koncovek, délku LED pásku, prostor pro vstup vodiče do profilu a pro připojení vodiče k LED pásku',
  'Zvolte délku napájecího vodiče LED pásku': 'Zvolte délku napájecího vodiče LED pásku',
  'Celková maximální doporučená délka napájecího vodiče (průřez 0,5 mm2) je pro tento typ LED pásku': 'Celková maximální doporučená délka napájecího vodiče (průřez 0,5 mm2) je pro tento typ LED pásku',
  'Zvolená délka': 'Zvolená délka',
  'Přívod': 'Přívod',
  'Zvolit': 'Zvolit',
  'Délka napájení': 'Délka napájení',
  'Délka pásku': 'Délka pásku',
  'Zvolte délku profilu': 'Zvolte délku profilu',
  'Výchozí': 'Výchozí nastavení',
  'Cena vzestupně': 'Cena vzestupně',
  'Cena sestupně': 'Cena sestupně',
  'Kód vzestupně': 'Kód vzestupně',
  'Kód sestupně': 'Kód sestupně',
  'Název vzestupně': 'Název vzestupně',
  'Název sestupně': 'Název sestupně',
  'Základní filtr': 'Základní filtr',
  'Rozšířený filtr': 'Rozšířený filtr',
  'Patice': 'Patice',
  'Výška': 'Výška',
  'chip': 'chip',
  'Napájení': 'Napájení',
  'Příkon': 'Příkon',
  'Šířka': 'Šířka',
  'Barvy': 'Barvy',
  'Náhrada za': 'Náhrada za',
  'Typ trubice': 'Typ trubice',
  'E-mail / Login': 'E-mail / Login',
  'Heslo': 'Heslo',
  'Přihlásit': 'Přihlásit',
  'Zapomenuté heslo': 'Zapomenuté heslo',
  'Neplatné jméno nebo heslo.': 'Neplatné jméno nebo heslo.',
  'Zadejte login a heslo.': 'Zadejte login a heslo.',
  'Přihlásit se': 'Přihlásit se',
  'Odhlásit': 'Odhlásit',
  'Česky': 'Česky',
  'Newsletter': 'Newsletter',
  'Nechte si zasílat novinky o výhodných akcích': 'Nechte si zasílat novinky o výhodných akcích',
  'Přihlášení uživatele': 'Přihlášení uživatele',
  'Pokud u nás nemáte založený účet, můžete se registrovat': 'Pokud u nás nemáte založený účet, můžete se registrovat',
  'Nová registrace': 'Nová registrace',
  'Děkujeme za objednávku': 'Děkujeme za objednávku',
  'Vážený zákazníku': 'Vážený zákazníku',
  'objednávka byla přijata a její kopie zaslána na vaši e-mailovou adresu.': 'objednávka byla přijata a její kopie zaslána na vaši e-mailovou adresu.',
  'O jejím aktuálním stavu vás budeme informovat.': 'O jejím aktuálním stavu vás budeme informovat.',
  'Pokud máte nějaké dotazy či připomínky, neváhejte nás kontaktovat': 'Pokud máte nějaké dotazy či připomínky, neváhejte nás kontaktovat',
  'na tel. čísle': 'na tel. čísle',
  'nebo na e-mailu': 'nebo na e-mailu',
  'Načíst další': 'Načíst další',
  'Předchozí': 'Předchozí',
  'Další': 'Další',
  'Nakupujte u našich partnerů': 'Nakupujte u našich partnerů',
  'Registrace': 'Registrace',
  'Přihlašovací údaje': 'Přihlašovací údaje',
  'Login': 'Login',
  'Potvrdit heslo': 'Potvrdit heslo',
  'Chci se zároveň registrovat': 'Chci se zároveň registrovat',
  'Jméno': 'Jméno',
  'Příjmení': 'Příjmení',
  'Telefon': 'Telefon',
  'Město': 'Město',
  'Ulice': 'Ulice',
  'PSČ': 'PSČ',
  'Stát': 'Stát',
  'Firemní údaje': 'Firemní údaje',
  'Firma': 'Firma',
  'IČ': 'IČ',
  'DIČ': 'DIČ',
  'Dodací adresa je jiná než fakturační': 'Dodací adresa je jiná než fakturační',
  'Souhlasím se zasíláním novinek': 'Souhlasím se zasíláním novinek',
  'Registrovat': 'Registrovat',
  'Uložit': 'Uložit',
  'Poznámka': 'Poznámka',
  'Vaše registrace proběhla úspěšně': 'Vaše registrace proběhla úspěšně',
  'Přihlašovací údaje Vám byly zaslány na zadaný e-mail': 'Přihlašovací údaje Vám byly zaslány na zadaný e-mail',
  'Načítám dopravu a platbu': 'Načítám dopravu a platbu',
  'Podobné produkty': 'Podobné produkty',
  'Žádný podobný produkt nebyl nalezen': 'Žádný podobný produkt nebyl nalezen',
  'ks': 'ks',
  'Na objednání': 'Na objednání',

  'nepřihlášen': 'nepřihlášen',
  'Neplatný kupón': 'Neplatný kupón',
  'Chyba při mazání kupónu': 'Chyba při mazání kupónu',
  'Nepodařilo se vložit kupón': 'Nepodařilo se vložit kupón',
  'Nepodařilo se vytvořit objednávku': 'Nepodařilo se vytvořit objednávku',
  'V košíku nemáte žádné zboží': 'V košíku nemáte žádné zboží',
  'Není vybraný způsob dopravy': 'Není vybraný způsob dopravy',
  'Není vybraný způsob platby': 'Není vybraný způsob platby',
  'Není zadáno jméno uživatele': 'Není zadáno jméno uživatele',
  'Není zadáno příjmení uživatele': 'Není zadáno příjmení uživatele',
  'Není zadán email uživatele': 'Není zadán email uživatele',
  'Nepodařilo se přihlásit': 'Nepodařilo se přihlásit',
  'Nepodařilo se odhlásit': 'Nepodařilo se odhlásit',
  'Chybné jméno nebo heslo': 'Chybné jméno nebo heslo',
  'Login není vyplněn': 'Login není vyplněn',
  'Uživatelský profil byl uložen': 'Uživatelský profil byl uložen',
  'Email je neplatný': 'Email je neplatný',
  'Telefon je neplatný': 'Telefon je neplatný',
  'PSČ je neplatné': 'PSČ je neplatné',
  'Jméno není vyplněno': 'Jméno není vyplněno',
  'Příjmení není vyplněno': 'Příjmení není vyplněno',
  'Email není vyplněn': 'Email není vyplněn',
  'Telefon není vyplněn': 'Telefon není vyplněn',
  'Ulice není vyplněna': 'Ulice není vyplněna',
  'Město není vyplněno': 'Město není vyplněno',
  'PSČ není vyplněno': 'PSČ není vyplněno',
  'Heslo není vyplněno': 'Heslo není vyplněno',
  'Heslo a heslo pro ověření musí být stejné': 'Heslo a heslo pro ověření musí být stejné',
  'Heslo pro ověření není vyplněno': 'Heslo pro ověření není vyplněno',
  'Zadaný login již existuje, zadejte prosím jiný.': 'Zadaný login již existuje, zadejte prosím jiný.',
  'Uživatel se zadaným emailem již existuje, zadejte prosím jiný.': 'Uživatel se zadaným emailem již existuje, zadejte prosím jiný.',
  'Chyba při vytváření uživatele.': 'Chyba při vytváření uživatele.',
  'Chyba při ukladani uživatele.': 'Chyba při ukladani uživatele.',
  'Chyba při vkládání do košíku': 'Chyba při vkládání do košíku',
  'Neplatný email': 'Neplatný email',
  'Email byl zaregistrován pro zasílání novinek': 'Email byl zaregistrován pro zasílání novinek',
  'Řetětec musí obsahovat alespoň 3 znaky': 'Řetětec musí obsahovat alespoň 3 znaky',
  '-- nevyplněno --': '-- nevyplněno --',
  'Dotaz byl odeslán': 'Dotaz byl odeslán',
  'Dotaz nebyl odeslán, došlo k chybě': 'Dotaz nebyl odeslán, došlo k chybě',
  'Nenalezen žádný záznam': 'Nenalezen žádný záznam',
  'Ano': 'Ano',
  'Ne': 'Ne',
  'ANO': 'ANO',
  'NE': 'NE',
  'Novinky': 'Novinky',
  'Očekáváme': 'Očekáváme',
  'Převodem': 'Bank transfer',
  'Bankovním převodem - proforma': 'Bankovním převodem - proforma',
  'Hotově (nelze platit kartou)': 'Hotově (nelze platit kartou)',
  'Platba při dobírce': 'Platba při dobírce',
  'Přepravce': 'Přepravce',
  'Osobně': 'Osobně',
  'Kód produktu': 'Kód produktu',
  'Typ produktu': 'Typ produktu',
  'Rakousko': 'Rakousko',
  'Česká republika': 'Česká republika',
  'Česko': 'Česko',
  'Název': 'Název',
  'Cena': 'Cena',
  'McLED s.r.o., Vídeňská 185, 252 42 Jesenice': 'McLED s.r.o., Vídeňská 185, 252 42 Jesenice',
  'Pan':'Pan',
  'Paní':'Paní',
  'Oslovení':'Oslovení',
  'Pro firemní zákazníky nabízíme výhodné nákupní podmínky':'Pro firemní zákazníky nabízíme výhodné nákupní podmínky',
  'Děkuji, nemám zájem':'Děkuji, nemám zájem',
  'Mám zájem o sjednání obchodních podmínek pro firemní zákazníky (B2B)':'Mám zájem o sjednání obchodních podmínek pro firemní zákazníky (B2B)',
  'Předmět podnikání':'Předmět podnikání',
  'Webová adresa':'Webová adresa',
  'Nákupní podmínky':'Nákupní podmínky',
  'Váš požadavek byl odeslán.':'Váš požadavek byl odeslán.',
  'Děkujeme Vám, že máte zájem stát se našimi B2B obchodními partnery.':'Děkujeme Vám, že máte zájem stát se našimi B2B obchodními partnery.',
  'Nejpozději do 24h Vás bude kontaktovat naše obchodní oddělení.':'Nejpozději do 24h Vás bude kontaktovat naše obchodní oddělení.',
  'V případě zájmu jej neváhejte sami kontaktovat:':'V případě zájmu jej neváhejte sami kontaktovat:',
  'Firma není vyplněna': 'Firma není vyplněna',
  'IČ není vyplněno': 'IČ není vyplněno',
  'DIČ není vyplněno': 'DIČ není vyplněno',
  'Předmět podnikání není vyplněn': 'Předmět podnikání není vyplněn',
  'Přihlašovací e-mail / Login': 'Přihlašovací e-mail / Login',
  'Přihlašovací e-mail': 'Přihlašovací e-mail',
  'Přihlašovací email je neplatný': 'Přihlašovací email je neplatný',
  'Objednání po překročení kreditního limitu': 'Objednání po překročení kreditního limitu',
  'Zavřít': 'Zavřít',
  'Čekejte prosím, ukládá se množství.': 'Čekejte prosím, ukládá se množství.',
  'Zpět na přihlášení': 'Zpět na přihlášení',
  'Firma není platná': 'Firma není platná',
  'IČ není platné': 'IČ není platné',
  'DIČ je neplatné': 'DIČ je neplatné',
  'v hotovosti': 'v hotovosti',
  'jejich cena bez DPH': 'jejich cena bez DPH',
  'Váš uživatelský účet má schválené B2B podmínky pro stát ': 'Váš uživatelský účet má schválené B2B podmínky pro stát ',
  'Přihlaste se prosím na webu příslušného státu pomocí tohoto odkazu: ': 'Přihlaste se prosím na webu příslušného státu pomocí tohoto odkazu: ',
  'Chyba při odeslání požadavku.': 'Chyba při odeslání požadavku.',
  'Heslo bylo zasláno na Váš email.': 'Heslo bylo zasláno na Váš email.',
  'Ceny jsou uvedeny bez DPH': 'Ceny jsou uvedeny bez DPH',
  'DPC bez DPH': 'DPC bez DPH',
  'vaše cena': 'vaše cena',
  'Celková cena bez DPH': 'Celková cena bez DPH',
  'Dodání do svou pracovních dní při objednávce do 10 hodin.': 'Dodání do svou pracovních dní při objednávce do 10 hodin.',
  'Zboží bude odesláno a fakturováno firmou McLED s.r.o. (Česká republika).': 'Zboží bude odesláno a fakturováno firmou McLED s.r.o. (Česká republika).',
  'Heslo nemá správný tvar (délka minimálně 8 číslic, 1x velké písmeno, 1x malé písmeno, 1x číslice)': 'Heslo nemá správný tvar (délka minimálně 8 číslic, 1x velké písmeno, 1x malé písmeno, 1x číslice)',
};
